[package]
name = "boo"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2"
crossterm = "0.27"
crossbeam = "0.8.3"
libc = "0.2"
parking_lot = "0.12.1"
